# Generated by Django 5.1.6 on 2025-02-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['title']},
        ),
    ]
